/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bancodados1;

import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Layanne55896236
 */
public class TelaInicial extends javax.swing.JFrame {

    /**                                                                 
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        mPrincipal.setVisible(false);
        mControleAcesso.setVisible(false);
    }
                                            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel = new javax.swing.JDesktopPane();
        lbUsuario = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        lbSenha = new javax.swing.JLabel();
        senha = new javax.swing.JPasswordField();
        btEntra = new javax.swing.JButton();
        mPrincipal = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mCadastroPessoa = new javax.swing.JMenuItem();
        mCasdastroProduto = new javax.swing.JMenuItem();
        mDeslogar = new javax.swing.JMenu();
        mControleAcesso = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbUsuario.setText("Usuario:");

        lbSenha.setText("Senha:");

        btEntra.setText("Entra no Sistema");
        btEntra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btEntraMouseClicked(evt);
            }
        });

        painel.setLayer(lbUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel.setLayer(usuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel.setLayer(lbSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel.setLayer(senha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        painel.setLayer(btEntra, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(417, 417, 417)
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbSenha)
                            .addComponent(lbUsuario))
                        .addGap(25, 25, 25)
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(senha)))
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(461, 461, 461)
                        .addComponent(btEntra)))
                .addContainerGap(688, Short.MAX_VALUE))
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbUsuario))
                .addGap(49, 49, 49)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSenha)
                    .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(btEntra)
                .addContainerGap(389, Short.MAX_VALUE))
        );

        jMenu1.setText("Cadastro");

        mCadastroPessoa.setText("CadastroPessoa");
        mCadastroPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCadastroPessoaActionPerformed(evt);
            }
        });
        jMenu1.add(mCadastroPessoa);

        mCasdastroProduto.setText("CadastroProduto");
        mCasdastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCasdastroProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(mCasdastroProduto);

        mPrincipal.add(jMenu1);

        mDeslogar.setText("deslogar");
        mDeslogar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mDeslogarMouseClicked(evt);
            }
        });
        mPrincipal.add(mDeslogar);

        mControleAcesso.setText("Controle de Acesso");
        mControleAcesso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mControleAcessoMouseClicked(evt);
            }
        });
        mControleAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mControleAcessoActionPerformed(evt);
            }
        });
        mPrincipal.add(mControleAcesso);

        setJMenuBar(mPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mCadastroPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCadastroPessoaActionPerformed
        CadastroPessoa cp = new  CadastroPessoa ();
        painel.add(cp);
        cp.setVisible(true);

    }//GEN-LAST:event_mCadastroPessoaActionPerformed

    private void mCasdastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCasdastroProdutoActionPerformed
         CadastroProduto cp = new  CadastroProduto();
          painel.add(cp);
         cp.setVisible(true);
    }//GEN-LAST:event_mCasdastroProdutoActionPerformed

    private void btEntraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btEntraMouseClicked
             
        try {
            Connection con = ConexaoMysql.conexaoBanco();
            String sql= "SELECT * FROM login WHERE usuario = ? "
                    + "AND senha = UPPER(MD5(?))";
                   
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1,usuario.getText());
            stmt.setString(2,senha.getText());
            ResultSet rs = stmt.executeQuery();

            if(rs.next()){
                String tipoUsuario =rs.getString("tipo_usuario");
                String situacao = rs.getString("situacao");
                String resetarSenha = rs.getString("resetar_senha");
                String codigoUsuario = rs.getString("id_login");
                
                if(tipoUsuario.equals("Admin")
                        && situacao.equals("A") && resetarSenha.equals("N")){
                mControleAcesso.setVisible(true);
                mPrincipal.setVisible(true);
                lbUsuario.setVisible(false);
                lbSenha.setVisible(false);
                usuario.setVisible(false);
                senha.setVisible(false);
                btEntra.setVisible(false);
                usuario.setText(null);
                senha.setText(null);
            }else if (tipoUsuario.equals("Admin")
                  && situacao.equals("A")&& resetarSenha.equals("S")){ 
                JOptionPane.showMessageDialog(null, "voce precisa gera senha");
                  ResetaSenha trs = new ResetaSenha();
                  trs.codigo.setText(codigoUsuario);
                  trs.usuario.setText(usuario.getText());
                  painel.add(trs);
                  trs.setVisible(true);
             }}else{
                JOptionPane.showMessageDialog(null,"Usuario Senha Icorreta!!!");
                
            }  
                
            
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
            
       
        
    }//GEN-LAST:event_btEntraMouseClicked

    private void mDeslogarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mDeslogarMouseClicked
             mPrincipal.setVisible(false);
                lbUsuario.setVisible(true);
                lbSenha.setVisible(true);
                usuario.setVisible(true);
                senha.setVisible(true);
                btEntra.setVisible(true);
             
         
    }//GEN-LAST:event_mDeslogarMouseClicked

    private void mControleAcessoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mControleAcessoMouseClicked
               ControleAcesso ca = new ControleAcesso();
               painel.add(ca);
               ca.setVisible(true);
    }//GEN-LAST:event_mControleAcessoMouseClicked

    private void mControleAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mControleAcessoActionPerformed
              
    }//GEN-LAST:event_mControleAcessoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEntra;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JMenuItem mCadastroPessoa;
    private javax.swing.JMenuItem mCasdastroProduto;
    private javax.swing.JMenu mControleAcesso;
    private javax.swing.JMenu mDeslogar;
    private javax.swing.JMenuBar mPrincipal;
    private javax.swing.JDesktopPane painel;
    public javax.swing.JPasswordField senha;
    public javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables

    private static class situacao {

        public situacao() {
        }
    }
}
